// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using dotNET_HW2.PageObjects;
 
namespace  dotNET_HW2.TestClasses 

{

[TestFixture]
public class Tests  : BasePage {

  [OneTimeSetUp]
  public void SetUp() {

    Initialize();
    
  }

  [Test]
  public void addToBasketTest() {

    HomePage homepage = new HomePage(driver);

    homepage.searchProduct("Fındıklı Çikolata");
    homepage.addToBasket();
    homepage.completeShopping();
    Assert.That(driver.FindElement(By.CssSelector(".BasketAccount > div:nth-of-type(1) > .button")).Text, Is.EqualTo("SİPARİŞİ TAMAMLA "));
  }

  [Test]
   public void removeFromBasketTest() {

    HomePage homepage = new HomePage(driver);

    homepage.searchProduct("Kahve");
    homepage.addToBasket();
    Assert.That(driver.FindElement(By.CssSelector(".Text > .T")).Text, Is.EqualTo("Sepetinizde ürün bulunmamaktadır."));
   }
  
  [OneTimeTearDown]
  protected void Close() {
    TearDown();
  }


}}








